### PR TITLE
Rewrite documentation using hugo

### PR DESCRIPTION
**Pull request by Kdecherf**
This PR rewrites the documentation using [hugo](https://gohugo.io/) and theme [hextra](https://github.com/imfing/hextra).

You may prefer to review it commit by commit.

Changes:
- [x] Remove DE and IT translations
- [x] Fix titles and callouts
- [x] Fix images
- [x] Check if redirects are needed for search engines

Notes: FR has been removed for now, I'm waiting a first review before going on with fixing FR as well

### CODE REVIEW

**Comment by Strubbl** [comment]
> It also removes DE and IT translations.

Why?

**Comment by Kdecherf** [comment]
@Strubbl see #88

**Comment by Strubbl** [comment]
If you are interested, I could invest some time to keep DE synced, but it would be nice to have some tooling support for this task. So that i do not have to find out the missing bits and pieces manually.

**Comment by Kdecherf** [comment]
I don't know what kind of tooling we could use for that. I don't think weblate and cie would do the job for this kind of content and translations.

Which part would be the most valuable in DE for you? User part only? All?

**Comment by Strubbl** [comment]
Too bad. Without a tooling support to keep track of changes in the original documentation, it makes no sense to keep the DE translation. It would be outdated soon again.

**Comment by Kdecherf** [comment]
@j0k3r I've updated the main pages with some cards, what do you think?
- https://deploy-preview-186--wallabag-doc.netlify.app/user/
- https://deploy-preview-186--wallabag-doc.netlify.app/apps/
- https://deploy-preview-186--wallabag-doc.netlify.app/admin/
- https://deploy-preview-186--wallabag-doc.netlify.app/developer/

**Comment by j0k3r** [comment]
@Kdecherf I like it!

**Comment by nicosomb** [comment]
it looks nice

**Comment by j0k3r** [comment]
Looks great, you can squash :+1:

**Review by nicosomb — APPROVED** [review]

**Comment by Kdecherf** [comment]
The PR is finally ready :tada:

**Review by j0k3r — APPROVED** [review]

**Pull request merged**
