### PR TITLE
Improve phrasing on admin and development docs

### PR DESCRIPTION
**Pull request by RayBB**
Following up on https://github.com/wallabag/doc/pull/190#issuecomment-2455041670 went through the admin and development docs and tried to make them a bit clearer.

Please feel free to commit directly to this branch or comment with suggestions if you feel anything is off.

If this is satisfactory I'll give a pass at the documentation in the user folder too.

Trying to strike a balance between not changing too much in an opinionated way and making things as clear as possible :)

### CODE REVIEW

**Comment by Kdecherf** [comment]
Hello @RayBB,

I've finally merged a rewrite of the documentation using a newer engine. Would you like some help for rebasing your work?

**Comment by RayBB** [comment]
@Kdecherf that would be great!

**Comment by Kdecherf** [comment]
@RayBB I've rebased your PR, could you check that I didn't miss anything?

**Comment by RayBB** [comment]
@Kdecherf just double checked and it looks good to me. Thanks for doing that :)

**Review by j0k3r — APPROVED** [review]

**Pull request merged**
