### PR TITLE
Add php-sockets extension in requirements

### PR DESCRIPTION
**Pull request by yoanmalie**
Hello,
This extension was needed during my installation to make it work and it's not listed yet on the doc so here it is!

### CODE REVIEW

**Comment by j0k3r** [comment]
How are you connecting to your database? Using socket?

**Comment by yoanmalie** [comment]
@j0k3r I probably don't use it but if I remember it was required during `make install`, (trought Composer ?).

**Comment by j0k3r** [comment]
Any change to retrieve the output of `make install` to track why it was required?

**Comment by j0k3r** [comment]
@yoanmalie 👋

**Comment by yoanmalie** [comment]
Sorry for the lack of reply, i'm a little bit busy at this time. I gave up my attempts with Wallabag and keep opened too many tabs on my browser instead 👀🙈.

I should start over a new installation when I will find time! I think we can close this PR since it's maybe a mistake on my part.

**Pull request closed without merging**
