### PR TITLE
Add warning for DE & IT translations

### PR DESCRIPTION
**Pull request by techexo**
Following #88, I added a warning to all DE & IT translations containing a link towards the English documentation.

### CODE REVIEW

**Comment by tcitworld** [comment]
Maybe add also something like "You can contribute to this documentation on [Github](https://github.com/wallabag/doc)"

**Comment by techexo** [comment]
@tcitworld I'll add your suggestion if and when a consensus has been found in #88.

**Comment by j0k3r** [comment]
Could you rebase it against the master? So we'll have a preview url for the documentation from your PR.

**Comment by techexo** [comment]
Actually I'm away from my computer for almost three weeks. Could I give you somehow write access to my github repo?

**Comment by j0k3r** [comment]
@techexo no problem, I've done it for you. Enjoy your 3 weeks away!

**Comment by nicosomb** [comment]
Maybe on the DE documentation we can put a text in german. Same thing for the italian documentation.

**Comment by j0k3r** [comment]
I've put basic _Google Translate_ translation for the warning message.

**Pull request merged**
