### PR TITLE
Italian translation update

### PR DESCRIPTION
**Pull request by matteocoder**
This is the revised italian translation, based on the english version available on the master branch at the moment.

### CODE REVIEW

**Comment by j0k3r** [comment]
Could you rebase your brand against the master?

**Comment by matteocoder** [comment]
@j0k3r Do you mean against wallabag/master? Wasn't using git rebase -i on matteocoder/master enough?

**Comment by j0k3r** [comment]
If you don't update matteocoder/master from wallabag/master, nope, it's not enough

**Comment by matteocoder** [comment]
@j0k3r [This is what I should do right?](https://help.github.com/articles/syncing-a-fork/) Is there something else I should do then or will you be able to merge the pull request without problems?

**Comment by j0k3r** [comment]
After that it'll be ok, just do `git rebase upstream/master` instead of `git merge upstream/master`

**Comment by matteocoder** [comment]
@j0k3r I think it should be ok now, I encountered some merging conflicts along the way but I think they are solved now (probably due to the fact that when using git rebase -i on my master branch on my 67 commits also included for some reason your commit too). Thank you very much for your patience!

**Comment by j0k3r** [comment]
Good job about that translation :+1:

**Pull request merged**
